name: Deploy API

# Azure deploy only when code is pushed to main
on:
  push:
    branches:
      - main
    paths:
      - 'PersonalFinance.Api/**'
      - 'PersonalFinance.Core/**'
      - 'PersonalFinance.Infrastructure/**'
      - '.github/workflows/deploy-api.yml'

env:
  AZURE_WEBAPP_NAME: personalfinance-api
  DOTNET_VERSION: '10.0.x'
  PROJECT_PATH: './PersonalFinance.Api/PersonalFinance.Api.csproj'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ./publish --no-build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./publish
